name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      ngrok:
        description: 'ngrok auth token'
        required: true
 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install curl wget qemu-kvm -y
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xf ngrok-v3-stable-linux-amd64.tgz
          chmod +x ngrok
          ./ngrok config add-authtoken "${{ github.event.inputs.ngrok }}"
          nohup ./ngrok tcp --region ap 5900 &>/dev/null &
      - name: cài win và khởi chạy
        run: |
          wget -O install.sh https://raw.githubusercontent.com/ubuntu2310fake/highspecwindows/main/install.sh
          chmod +x install.sh
          sudo ./install.sh
