name: test cpu ram

on: 
  workflow_dispatch:
    inputs:
      ngrok:
        description: 'ngrok auth token'
        required: false
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test cpu ram neofetch
        run: |
          sudo apt update -y
          sudo apt install neofetch -y
          neofetch
          lscpu
          free -m
          lsblk
